#include "sqlite_enums.hpp"

using namespace godot;

void SQLiteEnums::_bind_methods() {
    // Constants.
	BIND_ENUM_CONSTANT(RC_SQLITE_OK); /* Successful result */
	/* beginning-of-error-codes */
	BIND_ENUM_CONSTANT(RC_SQLITE_ERROR);
	BIND_ENUM_CONSTANT(RC_SQLITE_INTERNAL);
	BIND_ENUM_CONSTANT(RC_SQLITE_PERM);
	BIND_ENUM_CONSTANT(RC_SQLITE_ABORT);
	BIND_ENUM_CONSTANT(RC_SQLITE_BUSY);
	BIND_ENUM_CONSTANT(RC_SQLITE_LOCKED);
	BIND_ENUM_CONSTANT(RC_SQLITE_NOMEM);
	BIND_ENUM_CONSTANT(RC_SQLITE_READONLY);
	BIND_ENUM_CONSTANT(RC_SQLITE_INTERRUPT);
	BIND_ENUM_CONSTANT(RC_SQLITE_IOERR);
	BIND_ENUM_CONSTANT(RC_SQLITE_CORRUPT);
	BIND_ENUM_CONSTANT(RC_SQLITE_NOTFOUND);
	BIND_ENUM_CONSTANT(RC_SQLITE_FULL);
	BIND_ENUM_CONSTANT(RC_SQLITE_CANTOPEN);
	BIND_ENUM_CONSTANT(RC_SQLITE_PROTOCOL);
	BIND_ENUM_CONSTANT(RC_SQLITE_EMPTY);
	BIND_ENUM_CONSTANT(RC_SQLITE_SCHEMA);
	BIND_ENUM_CONSTANT(RC_SQLITE_TOOBIG);
	BIND_ENUM_CONSTANT(RC_SQLITE_CONSTRAINT);
	BIND_ENUM_CONSTANT(RC_SQLITE_MISMATCH);
	BIND_ENUM_CONSTANT(RC_SQLITE_MISUSE);
	BIND_ENUM_CONSTANT(RC_SQLITE_NOLFS);
	BIND_ENUM_CONSTANT(RC_SQLITE_AUTH);
	BIND_ENUM_CONSTANT(RC_SQLITE_FORMAT);
	BIND_ENUM_CONSTANT(RC_SQLITE_RANGE);
	BIND_ENUM_CONSTANT(RC_SQLITE_NOTADB);
	BIND_ENUM_CONSTANT(RC_SQLITE_NOTICE);
	BIND_ENUM_CONSTANT(RC_SQLITE_WARNING);
	BIND_ENUM_CONSTANT(RC_SQLITE_ROW);
	BIND_ENUM_CONSTANT(RC_SQLITE_DONE);
	BIND_ENUM_CONSTANT(RC_GDSQLITE_ERROR);
	/* end-of-error-codes */

	BIND_ENUM_CONSTANT(QUIET);
	BIND_ENUM_CONSTANT(NORMAL);
	BIND_ENUM_CONSTANT(VERBOSE);
	BIND_ENUM_CONSTANT(VERY_VERBOSE);
}
