#ifndef SQLITE_ENUMS_CLASS_H
#define SQLITE_ENUMS_CLASS_H

#include <godot_cpp/classes/ref_counted.hpp>
#include <sqlite/sqlite3.h>

namespace godot {

class SQLiteEnums : public RefCounted {
    GDCLASS(SQLiteEnums, RefCounted);

protected:
    static void _bind_methods();

public:
    // Constants.
	enum ResultCode {
		RC_SQLITE_OK = SQLITE_OK,
		RC_SQLITE_ERROR = SQLITE_ERROR,
		RC_SQLITE_INTERNAL = SQLITE_INTERNAL,
		RC_SQLITE_PERM = SQLITE_PERM,
		RC_SQLITE_ABORT = SQLITE_ABORT,
		RC_SQLITE_BUSY = SQLITE_BUSY,
		RC_SQLITE_LOCKED = SQLITE_LOCKED,
		RC_SQLITE_NOMEM = SQLITE_NOMEM,
		RC_SQLITE_READONLY = SQLITE_READONLY,
		RC_SQLITE_INTERRUPT = SQLITE_INTERRUPT,
		RC_SQLITE_IOERR = SQLITE_IOERR,
		RC_SQLITE_CORRUPT = SQLITE_CORRUPT,
		RC_SQLITE_NOTFOUND = SQLITE_NOTFOUND,
		RC_SQLITE_FULL = SQLITE_FULL,
		RC_SQLITE_CANTOPEN = SQLITE_CANTOPEN,
		RC_SQLITE_PROTOCOL = SQLITE_PROTOCOL,
		RC_SQLITE_EMPTY = SQLITE_EMPTY,
		RC_SQLITE_SCHEMA = SQLITE_SCHEMA,
		RC_SQLITE_TOOBIG = SQLITE_TOOBIG,
		RC_SQLITE_CONSTRAINT = SQLITE_CONSTRAINT,
		RC_SQLITE_MISMATCH = SQLITE_MISMATCH,
		RC_SQLITE_MISUSE = SQLITE_MISUSE,
		RC_SQLITE_NOLFS = SQLITE_NOLFS,
		RC_SQLITE_AUTH = SQLITE_AUTH,
		RC_SQLITE_FORMAT = SQLITE_FORMAT,
		RC_SQLITE_RANGE = SQLITE_RANGE,
		RC_SQLITE_NOTADB = SQLITE_NOTADB,
		RC_SQLITE_NOTICE = SQLITE_NOTICE,
		RC_SQLITE_WARNING = SQLITE_WARNING,
		RC_SQLITE_ROW = SQLITE_ROW,
		RC_SQLITE_DONE = SQLITE_DONE,
		RC_GDSQLITE_ERROR = 10000
	};

    enum VerbosityLevel {
        QUIET = 0,
        NORMAL = 1,
        VERBOSE = 2,
        VERY_VERBOSE = 3
    };
};

} //namespace godot

VARIANT_ENUM_CAST(SQLiteEnums::ResultCode);
VARIANT_ENUM_CAST(SQLiteEnums::VerbosityLevel);

#endif // SQLITE_ENUMS_CLASS_H