name: 🤖 Android Builds
on:
  push:
    branches: [ master, main, vfs-testing ]
    
# Global Settings
# Only use the release target for android, otherwise further modification of the make-files is required!
env:
  PROJECT_FOLDER: .
  TARGET_PATH: demo/addons/godot-sqlite/bin/android/
  TARGET_NAME: libgdsqlite
  TARGET: release

jobs:
  android-compilation:
    name: Android Compilation
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
        with:
            lfs: true
            submodules: recursive

      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      # Use python 3.x release (works cross platform)
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Compilation
        env:
          ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk-bundle
        run: |
          mkdir -v -p ${{env.PROJECT_FOLDER}}/${{env.TARGET_PATH}}/armeabi-v7a
          mkdir -v -p ${{env.PROJECT_FOLDER}}/${{env.TARGET_PATH}}/arm64-v8a
          mkdir -v -p ${{env.PROJECT_FOLDER}}/${{env.TARGET_PATH}}/x86
          cd ${{env.PROJECT_FOLDER}}
          cd godot-cpp
          scons platform=android bits=64 android_arch=armv7 target=${{env.TARGET}} generate_bindings=yes -j4
          scons platform=android bits=64 android_arch=arm64v8 target=${{env.TARGET}} generate_bindings=yes -j4
          scons platform=android bits=64 android_arch=x86 target=${{env.TARGET}} generate_bindings=yes -j4
          cd ..
          $ANDROID_NDK_ROOT/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk APP_PLATFORM=android-21 NDK_LIBS_OUT=./${{env.TARGET_PATH}}
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: android
          path: ${{env.PROJECT_FOLDER}}/${{env.TARGET_PATH}}
