name: Gut

on:
  pull_request:
  push:
    branches: [ master, main ]

jobs:
  gut:
    runs-on: ubuntu-latest
    container:
      image:
        barichello/godot-ci:3.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Gut (gut.sh)
        run: |
          cd demo/
          godot -s --path $PWD addons/gut/gut_cmdln.gd -gdir=res://tests -glog=1 -ginclude_subdirs -gexit
