# NOTE: The content of this file has been directly adapted from /godot-cpp/.workflows/static_checks.yml
name: 📊 Static Checks
on: [push, pull_request]

jobs:
  static-checks:
    name: Format (clang-format)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      # Azure repositories are not reliable, we need to prevent Azure giving us packages.
      - name: Make apt sources.list use the default Ubuntu repositories
        run: |
          sudo rm -f /etc/apt/sources.list.d/*
          sudo cp -f godot-cpp/misc/ci/sources.list /etc/apt/sources.list
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main"
          sudo apt-get update

      - name: Install dependencies
        run: |
          sudo apt-get install -qq clang-format-15
          sudo update-alternatives --remove-all clang-format || true
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-15 100

      - name: Style checks via clang-format (clang_format.sh)
        run: |
          bash ./misc/scripts/clang_format.sh